version: '3.3'
services:
  db:
    container_name: we-road-mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=we-road
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_TCP_PORT=3306
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
  backend:
    container_name: we-road-nest-app
    image: nest-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 9000:9000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    restart: unless-stopped
volumes:
  my-db: